version: "3.5"

services:
  service-registry:
    build: .
    image: "demo-app-service-registry"
    container_name: demo-app-service-registry
    networks:
      - demo-app-network
    volumes:
      - "./log:/app/log"
    ports:
      - "8761:8761"

networks:
  demo-app-network:
    external: false
    name: demo-app-network


